# Generated by Django 5.1.4 on 2026-06-30 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_shipping_method_order_shipping_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
