# Generated by Django 5.1.4 on 2026-07-08 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_carrier_alter_order_status_orderevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pos_reference',
            field=models.CharField(blank=True, editable=False, max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='pos_synced_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
