# Generated by Django 5.1.4 on 2026-07-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_pos_reference_order_pos_synced_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
