# Generated by Django 5.1.4 on 2026-07-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_attribute_attributevalue_productattribute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='name_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
