# Generated by Django 5.1.4 on 2026-07-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_verified_user_two_factor_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_stores',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of stores this seller may own (set by a platform admin).'),
        ),
    ]
