# Generated by Django 5.1.4 on 2026-07-07 22:41

import apps.pos.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_possupplierconnection_posimportedproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possupplierconnection',
            name='api_key',
            field=apps.pos.fields.EncryptedTextField(),
        ),
    ]
