# Generated by Django 5.1.4 on 2026-07-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='max_employees',
            field=models.PositiveIntegerField(default=1, help_text='Maximum employees this store may add (set by a platform admin).'),
        ),
    ]
