# Generated by Django 5.1.4 on 2026-07-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_store_currency_egp'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_en',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
