# Generated by Django 5.1.4 on 2026-07-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_store_description_en_store_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='storemembership',
            name='permissions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
