# Generated by Django 5.1.4 on 2026-07-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_storemembership_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformTheme',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform theme',
            },
        ),
    ]
